export type ReferencePageId =
  | 'community'
  | 'beliefs'
  | 'infrastructure'
  | 'research'
  | 'legal'
  | 'future'
  | 'donations'

export type ReferencePageContent = {
  id: ReferencePageId
  title: string
  subtitle: string
  lines: ReadonlyArray<string>
}

export const REFERENCE_PAGES = [
  {
    id: 'community',
    title: 'Community',
    subtitle:
      'Meetings, events, ceremonies, membership, and spiritual organizations.',
    lines: [
      'Community Meetings, Events, and Ceremonies',
      'I. Monthly Meditation (Entheogen Vapor) Ceremony',
      'A. A 1-hour Zoom in a partnership with [Entheo Community](https://www.entheo.community)',
      '1. 5-minute introduction and breathwork meditation',
      '2. 15-minute low-dose entheogenic vapor session',
      'a) Recommended dose size is 5-15mg DMT, 3-5mg 5-MeO-DMT, or unweighed doses of THC, but it is ultimately up to the individual.',
      '3. 40-minute discussion of spirituality, entheogens, and any visions or thoughts that arose during the meditations.',
      'B. Entheogen use is NOT necessary, and neither is participation in the discussion, nor use of the camera at any point',
      '1. One can meditate however they wish during the 15 minutes.',
      '2. This allows those who',
      'a) Have never tried DMT (or other entheogens) to benefit from being able to see how they can be used responsibly and spiritually.',
      '(1) This will grow the general entheogenic community.',
      "b) Don't wish to use entheogens once per month, but still want to participate in a regular meditation and the spiritual discussions that follow the use of entheogens.",
      'C. Join our Telegram group chat [here](https://t.me/+ccL8NUffhuU0ZGJh) for more information and updates.',
      'II. Sober Spirituality Ceremony',
      'A. 1 Hour Zoom where we discuss spirituality and ways to improve [ORG](https://org-spirituality.netlify.app)',
      'B. Starting once per month',
      '1. [Help us decide on a day/time](https://www.when2meet.com/?34041601-tlm3R)',
      'III. Video Calls With Partner (or supported) Organizations (and/or Churches)',
      'A. [Weekly Assembly with Moshe Jacobson from Entheo Community](https://airtable.com/appbVGvgHR52W0qp5/shr8Q8Iz11qX8ZX4z?gO7uy=allRecords&detail=eyJwYWdlSWQiOiJwYWd3SlZYZEtyU09QSlZKMSIsInJvd0lkIjoicmVjRnpCaVRDS3BtNWlvdDAiLCJzaG93Q29tbWVudHMiOmZhbHNlLCJxdWVyeU9yaWdpbkhpbnQiOnsidHlwZSI6InBhZ2VFbGVtZW50IiwiZWxlbWVudElkIjoicGVsUmxPUllheTNtdEtVSG0iLCJxdWVyeUNvbnRhaW5lcklkIjoicGVsNDh1NXkwM2NvZ083dXkiLCJzYXZlZEZpbHRlclNldElkIjoic2ZzUWV6M2xmNVk5UDJiZVIifX0)',
      '1. Wednesdays, 10:30 AM-12:00 PM EST, via Google Meet',
      'B. [Psanctuary (The Mushroom Church) Service](https://zoom.us/j/92899681717?pwd=dkEyT2RlSkE2dFNxZnI1cnBGZk5rdz09)',
      '1. Sundays, 10:00-11:30 AM EST, via Zoom',
      'C. [Simple Presence](https://zoom.us/j/91052650207?pwd=M25UVERjcm16ZUNXaXN6UWRyWkh3UT09) (A Contemplative Prayer Community)',
      '1. Silent Meditation (Every day) 7:30-7:50 AM EST',
      '2. Qigong Meditation/Exercise MWFSat 7:55-8:20 AM EST',
      '3. (Non-entheogenic)',
      'D. [The Sacred Synthesis Low-5 Light Wand Ceremony](https://riverside.com/studio/psilo-toad)',
      '1. 1hr sober meditation + 1hr Low-dose 5-MeO-DMT "Jaguar Light Wand" vape pens',
      '2. 10:00 AM - 12:00 PM on the last Sunday of each month',
      '3. Links',
      'a) [About The Sacred Synthesis](https://www.skool.com/thesacredsynthesis/about)',
      'b) [Jaguar Light Wand](https://www.low-5.com/jaguar)',

      'IV. In-Person Ceremonies',
      'A. In 2025, we had several ceremonies with 4-7 people who sat in a circle, vaporized DMT, and discussed our spiritual beliefs as well as whatever else the sacrament brought up.',
      'B. In 2023-2024, we had several bonfires where various entheogens were consumed (up to 12 people), and spiritual discussions ensued.',
      'C. We aim to continue having these events as often as we can get a reasonable group together.',
      'V. Synthesis, Extraction, and Cultivation of Entheogens',
      'A. We currently have a basic DMT extraction guide (with the interest of harm reduction in mind).',
      '1. We aim to develop more guides and to one day allow for in-person and live-streamed extractions.',
      'B. The repetitive motions, intentions, and prayers that go into these rituals are deeply spiritual, and members should be allowed to take part in each step of the synthesis, extraction, or cultivation, as well as to pray over (and bless) each step. Members: Tripp Rachel Emily (Em) Chris Leo',
      'J. Lauren Stalemate [How To Join?](https://forms.gle/UGyPvcKs6sC2xBGq8) To join, you will need to fill out a form. Choose either a Public Membership (like above), a Private Membership, or the ability to leave Anonymous Posts, even without an official membership. [Telegram @Tripp_ORG](https://t.me/Tripp_ORG) or [Signal @Tripp_ORG.99](https://signal.group/#CjQKIGm_Gsu9Lp9V6c_CN2AUuxSZWDRoIXqCTqdxzOmkoLPGEhDbF-_FCaSutuy3paRe9sUX) with your preferred name, and I will make a copy of the sample document (above) for you to fill out. In this document, you will find the link to a [Telegram group chat](https://t.me/+ccL8NUffhuU0ZGJh) where you can connect with the majority of our public and private members, as well as other potential members.',
      "Member-only Voting Seniority Our goal is to have everyone have an equal say in ORG decisions, but we are unaware of the best way to mitigate concerns about seniority. Those who have been in the ORG the longest are likely to sway the votes of the next closest senior members. This will have a domino effect on the newest members, and it will thus be much harder for early ORG beliefs to be changed, even with a massive influx of new members. All members should do their best to hold others accountable for keeping all decisions and disputes to a majority rules vote (with each member's vote holding equal weight), and we should consider the use of an algorithm on the website/app that could anonymize and randomize beliefs for voting by other members. Another newer idea is to allow public members to post a new belief in an anonymous way and then see how many people vote for or against that belief. This would prevent people from voting in agreement (or disagreement) based on the username of the poster and not on the content of the belief. An even newer idea is to require all vote proposals and voting to be anonymous. We should be able to do this through the website (and later app). This prevents voters from being biased by knowing who proposed the vote. This thought occurred to me as I was about to suggest a vote for me to have control over the bank account.",
      "Churches/ Spiritual Organizations Please feel free to leave comments on your own reviews/experiences with any of these organizations/churches. Even if it is negative towards the ORG, we will not delete anyone's comment. We will eventually have an AI match-making service for people looking for spiritual community to sort the communities based on percentage of belief alignment, distance, supported entheogens, sacraments, etc., etc. The members should be able to choose what weight percentage is given to each of their selected conditions of interest.",
      'I. ORG',
      'A. About Us/Contact',
      'II. Entheo Community',
      'A. In November of 2025, ORG developed a partnership with EC because of their awesome entheogen safety training and ministry certification.',
      '1. New members who wish to receive entheogens from ORG (eventually) must first prove that they have completed the EC safety training and that they have made a donation to EC in order for them to continue improving their training.',
      '2. Joining EC as a member is optional but encouraged.',
      'a) Entheo Community Membership Application',
      'B. Weekly Assembly with Moshe Jacobson',
      '1. Wednesdays, 10:30 AM-12:00 PM EST, via Google Meet',
      'C. Also offers regular ceremonies in-person in GA and sometimes other states as well (like Tennessee and North Carolina).',
      'III. Psanctuary (The Mushroom Church)',
      'A. Also see https://ministries.psanctuary.org',
      'B. Sunday Service',
      '1. 10:00-11:30AM EST, via Zoom',
      'IV. Native American Church (NAC)',
      'A. Practices Peyotism and has been federally recognized.',
      'B. Unfortunately does not allow anyone under 21 to join (unless they already have family members in the church).',
      'C. In the official NAC documents, it states that the church allows for members to be members of other religions, which ORG and ECC also strongly support.',
      '1. Credit is due to George "Greg" Lake for teaching me this.',
      'D. It is ALSO IMPORTANT that the NAC considers Peyote to be a medicine as much as a sacrament.',
      '1. Something else George "Greg" Lake is very familiar with and has used to defend a client before, who was advertising the medical benefits of the DMT-containing Ayahuasca brew that was part of her church. This was due to the government claiming that her advertising Ayahuasca as also a medicine was somehow undercutting her religious sincerity.',
      '2. Also, Reverend Hunt Priest, notably the most well-known entheogenic-using Christian pastor and founder of Ligare (a Psychedelic society for Christians, mentioned later), has said before, "When the church is no longer focused on healing, then it\'s time to close the doors".',
      'E. Evidence supporting this (AND A LOT MORE ABOUT IT):',
      '1. Control/Command + F search Tripp for "Addressal of the Legitimacy of Using Entheogens/Psychedelics as Medicine. "',
      'V. There are MANY more organizations that I support but have not had time to add here.',
      'A. If you are a member and support any other Church (entheogenic or not), feel free to include them here. Other Resources For Members:',
      'I. Entheogen Vaporizer Rentals and Vaporization Guides',
      'II. Offerings',
      'A. Items that ORG offers for free to members (donations optional).',
      'III. Doctors Who Understand Psychedelics',
      'A. Dr. Emily Kulpa',
      "1. Recommended by Moshe (from Entheo Community) for someone interested in trying psychedelic mushrooms but has a heart condition and was seeking a doctor's advice on how to proceed.",
    ],
  },
  {
    id: 'beliefs',
    title: 'Beliefs',
    subtitle:
      'Majority-held ORG beliefs, spiritual principles, and member-submitted beliefs.',
    lines: [
      'Beliefs These are the beliefs that are held by the majority of the ORG members: For a belief to be transferred here, one or more members must comment their agreement (or disagreement) with a belief on another member\'s personal page. Until we have a website to do it automatically, we must then transfer it manually. The (#/#) shows the ratio of members who have taken the time to state their agreement (or disagreement) with the belief. The name after the numbers/comma shows who first put the belief in their ORG membership page. You can go to their page and "Find"or (CMD/Ctrl + F) search to find the belief. After reading it, you can highlight it and then two-finger click or go to the top bar and click"Insert > Comment" to leave any comments and/or to vote your agreement or disagreement. While here, you can also make suggestions on ways to improve the belief (whether through word choice, concept, grammar, etc.) We will then update the numbering and reorder the ORG beliefs with the ones with the most agreement at the top.',
      'I. We think God/ universe/ Great architect is limitless, infinite. As a result, any further definition would be incorrect. (3/3, Chris)',
      "II. We are grateful that we have love in this particular version of reality. It's a beautiful barometer or compass at very least. At any time, we can compare our actions to what love would do, and immediately we know the value of what we're up to. Any imperfections jump right out. (3/3, Chris)",
      "III. We ' re here to explore and learn, especially about love, and we're here to enjoy it, as wild and crazy as that sounds. (3/3, Chris)",
      "IV. Entheogens offer so much wisdom, power, humility, and freedom. We don't believe they let us communicate with entities in a spiritual realm. We know that they do. We're grateful for that and retain a childlike curiosity as to why. It's fun to explore and learn, although any \" answer\" is just a bundle of more questions. It's one amazing ride that is worth supporting. If we all start connecting and comparing notes, then we just might be surprised. (3/3, Chris)",
      'V. The Universal Creator gifted us entheogens (psychedelic and non-psychedelic) and intend ed them to have a multitude of uses, including, but not limited to: (2/2, Tripp)',
      'A. Theophany',
      '1. Allowing us to see and/or communicate with more clearly with The Universal Creator, spirits, entities, and angelic beings, which all can offer guidance.',
      'B. Therapies /Medicines',
      '1. Healing of illness often leads to a stronger spiritual connection.',
      'C. Creativity Catalysts of Ideas to Better Humanity',
      '1. The knowledge of how to make our lives and the universe better.',
      'a) Showing us our purpose and/or things that we need to change/improve.',
      'b) Guiding scientific discoveries that will',
      '(1) Lead to better/longer lives of all living beings',
      '(2) Provide better definitions of what The Universal Creator is AND what its purpose for creating everything was.',
      '2. This belief is what led to the idea of building a digital spiritual text with the means of being updated regularly as our beliefs change and/or improve as a result of acquiring new knowledge.',
      'D. Responsible Recreation (aka relaxati on)',
      "1. The majority of people 's first entheogenic spiritual experiences were an unintentiona l and unexpected outcome of what was initially intended to be recreation al, medical/therapeutic, or even by pure accident in earl ier times (as this was how each entheogen was first discovered).",
      "2. Responsible recreational use is its own form of therapy through means of uplifting one's mood (relaxation).",
      '3. For those who had unintended spiritual experiences from initially using psychedelics for responsible recreation (like myself), it often takes many psychedelic journeys as well as a few breakthrough experiences before a complete transition from responsible recreation to spiritual/religious use will occur.',
      'a) These " many psychedelic journeys" could take months to years, depending on the frequency of psychedelic/entheogen use.',
      '(1) Frequency can depend on access, interest, etc.',
      'b) "Breakthrough experiences" are more common with higher:',
      '(1) Purity',
      '(2) Dose',
      '(3) Efficacy',
      '(a) Molecule',
      'i) Example: DMT is more efficacious than Psilocybin Mushrooms',
      '(b) Route of Administration',
      'i) Example: Continuous IV of DMT is more efficacious than vaporizing it',
      'c) The transition should be considered complete when every experience starts with spiritual/ religious intentions.',
      '(1) Responsible recreation/relaxation still fits within spiritual/religious use IF care is taken to thank/appreciate The Universal Creator for providing us with molecules that help us achieve a higher quality of life.',
      '(a) This is no different than participating in a Church sports team or other recreational event, like how many churches offer table tennis and similar games on site to attract new members.',
      'E. Irresponsible Recreation (in rare cases)',
      '1. Irresponsibility of any sort should never be encouraged, but many people have still had unexpected spiritual experiences from irresponsible recreational use of psychedelics.',
      'a) For th ose who initially use psychedelics irresponsibly, it often takes many more psychedelic journeys before a complete transition to responsible recreation, and then spiritual/religious use will form. Nonetheless, it is nearly guaranteed to eventually happen if the quality and the dosages are adequately high AND serious problems from irresponsible use are relatively rare (despite the government-led stigmatization of psychedelics). See the section Religious Risk Assessment for more on determining an acceptable level of risk when spiritual growth is at stake.',
      'VI. That which created the universe and everything in it can be referred to by any word that conveys respect. (3/3, Tripp)',
      'A. Members, feel free to leave any names we may use here (we should one day vote on what name is used in official ORG documents):',
      '1. The Universal Creator',
      '2. The Creator',
      '3. God',
      '4. \u05d4\u05d5\u05d4\u05d9/YHWH /Yahweh',
      '5. Universe',
      '6. Great Architect',
      'VII. Christian beliefs',
      'A. Monotheism (2/2, Emily (Em))',
      'B. The trinity unity of God, meaning God is three persons in one essence--the Father, the Son, and the Holy Spirit. Each person is fully God. (1/2, Emily (Em))',
      'C. God is omniscient (2/2, Emily (Em))',
      'D. God is omnipotent (2/2, Emily (Em))',
      'E. God is a spirit, and they that worship Him must worship Him in spirit and in truth (John 4:24) (1.5/2, Emily (Em))',
      'F. God is omnipresent and exists in all dimensions/planes (2/2, Emily (Em))',
      'G. God is outside of time. He has always existed and will always exist (the Alpha & the Omega) (1.5/2, Emily (Em))',
      'VIII. Plant medicine should be more widely available to people. (3/3, Lauren)',
      'IX. Plant medicine brings you (us) closer to God and, just as importantly, brings us closer to ourselves. (3/3, Lauren) Religio us Risk Assessment (3/3, Tripp)',
      'I. Risks have always been a part of spirituality/religion, and the risk vs. benefit analysis of each ideology should be determined by the practicing individuals, not by any government.',
      "II. Although not necessary in an ideal world, sacrificing one's safety is often a spiritual decision made on behalf of one's religious beliefs. Because I come from a Christian background, I have mostly Christian analogies for this:",
      'A. Moses rescuing the Hebrews from Egypt.',
      "1. Like Moses confronting Pharaoh or the unknown at Sinai, entheogen users enter uncharted psychological and spiritual territories, risking mental instability, overwhelming experiences, societal stigma, and/or legal prosecution. Both require courage to surrender to a higher power -Moses to God's voice, users to the altered states psychedelics induce, which some describe as divine encounters. Moses' journey involved trusting God despite fear; similarly, psychedelic users must navigate uncertainty, trusting the process to reveal spiritual truths. However, while Moses' dangers were external (persecution, survival), the risks of entheogens are often internal (ego dissolution, psychological distress), yet both reflect a profound commitment to transcend fear for a deeper connection with the divine, and both risked imprisonment by a government that was in the wrong.",
      'B. Daniel, Shadrach, Meshach, and Abednego',
      "1. In Daniel 6, Daniel refus ed to stop praying and was thrown into the lions' den as punishment and survived. Later, in Daniel 10:2-3, Daniel mourned and fasted for three weeks, eating no rich food, meat, or wine, and not anointing himself, seeking spiritual understanding.",
      '2. Shadrach, Meshach, and Abednego refused to worship an idol, refused to recant, and were thus sentenced to death in a fiery furnace but survived.',
      '3. Like example #1, these early Christians risked death in order to keep their relationship with God, while modern-day entheogen users risk a life of imprisonment.',
      'C. Stephen',
      "1. His teachings, which challenged the necessity of the Temple and Mosaic customs, enraged members of the Synagogue of the Freedmen, who falsely accused him of blasphemy. Brought before the Sanhedrin, Stephen delivered a powerful speech (Acts 7), recounting Israel's history from Abraham to Yeshua (Jesus), accusing the Jewish leaders of rejecting God's prophets and betraying the Messiah. His words infuriated the council, and when he declared seeing Yeshua (Jesus) standing at God's right hand, they dragged him outside the city and stoned him to death, making him the first Christian martyr.",
      '2. This is analogous to all who have already served jail/prison time for possessing and/or sharing entheogens with others. It is not always a happy ending, but the truth will eventually prevail.',
      'D. David fighting Goliath.',
      '1. I have felt the spirit of David, and I am certain that others also feel his spirit as we do battle with governments much more powerful than ourselves, and fight not only for our own freedom, but also for the freedom of others whom we feel responsible for fighting for.',
      'a) I personally feel responsible for fighting for',
      '(1) Those currently benefiting from entheogens but feel forced to use them in silence and isolation,',
      '(2) Those who will benefit from entheogens in the future, including the unborn.',
      '(a) I deeply want laws restricting psychedelics and public opinion around the use of psychedelics as entheogens to change before I have children.',
      "i) I do not want my future children to be bullied because of their parents' uncommon spiritual beliefs, and yet this is nearly inevitable.",
      '(3) Those spirits of those who have already passed on and have yet to receive the public respect which they deserve for what they did to directly help the entheogenic community (and thus indirectly helped all future world communities).',
      'E. Paul',
      '1. Acts 9:9, Saul (later Paul) fasted for three days after his encounter with Yeshua (Jesus) on the road to Damascus',
      'F. Peter',
      '1. Acts 10:9-16: Through a prayer followed by a period of hunger, Peter was granted a vision from God.',
      'G. By the third century, fasting for significant events, such as before receiving the Eucharist or during times of crisis, was common.',
      '1. Many people, including my past self, Christian or not, have or still will fast for days for the purpose of having a spiritual vision.',
      'a) This can certainly be dangerous and unhealthy if done too often or for too long, and is something I no longer do because of the reliability and fewer dangers of using entheogens to produce the visions.',
      'H. It was not " safe" to be Jewish in Nazi-era Germany, and yet most Jews still chose to practice their religion despite the risks.',
      'I. There are many more examples, but the above stories highlight the resolve to prioritize spiritual conviction over safety, facing persecution or hardship for a transcendent purpose.',
      'III. Trip-sitters and guided group ceremonies can be beneficial for some people, but are neither beneficial nor necessary for all people.',
      'A. Moses did not bring a trip-sitter or friend on any of his many journeys to the top of Mount Sinai, where he would meet with God.',
      '1. Meeting God is something many people feared back then (and still do fear).',
      'a) Psychedelics/entheogens can often be a similarly " scary" experience, both during preparation and during the experience.',
      '2. This is analogous to using entheogens alone, which should be allowed and supported by all religious and spiritual entheogenists.',
      'a) My strongest spiritual experiences have been when I was using entheogens alone.',
      "b) Spiritual/religious organizations and governments should support their members' freedom to use entheogens alone while also ensuring safety via a training and certification program (when it is affordable). Ideally, the government should have the burden of funding such a program (and making it accessible), thus not placing a financial burden on newly forming religions and/or spiritual ideologies.",
      'B. Ultimately, the decision for a trip-sitter or a guided group ceremony should be left up to the individual, as they are more likely to have a spiritual and safe experience if they are most comfortable from the beginning.',
      'IV. I will end this section by highlighting that if the government cared about maximizing the safety of its citizens, while still keeping to realistic norms of risk and avoiding any burden to religion(s), the government would implement a way for its people to access safe, regulated, and affordable sacraments! Theology (Spiritual beliefs which help to define The ORG\'s " majority held" beliefs) (CMD + F search Tripp for any of the below to vote on them. I would not normally post a 1/1 vote, but I think it is very important that more people vote on these ASAP, and if any reader has a 1/1 of their own that they think is important, I will gladly post it here as well!)',
      'I. Perennialism (1/1, Tripp)',
      'A. The perennial philosophy, also referred to as perennialism and perennial wisdom, is a school of thought in philosophy and spirituality that posits that the recurrence of common themes across world religions illuminates universal truths about the nature of reality, humanity, ethics, and consciousness.',
      'II. Entheism (1/1, Tripp)',
      'A. entheism.org',
      'B. Entheism: the belief that the Divine is within and we are all interconnected as One.',
      'III. Animism (1/1, Tripp)',
      'A. The attribution of a soul to plants, inanimate objects, and natural phenomena.',
      'B. The belief in a supernatural power that organizes and animates the material universe',
      'C. Hervey',
      'C. Peoples et al.-" the belief that all \'natural\' things, such as plants, animals, and even such phenomena as thunder, have intentionality (or a vital force) and can have influence on human lives"',
      '1. Pg. 266 of Peoples,',
      'H. C., Duda, P., & Marlowe,',
      'F.',
      'W. (2016). Hunter-gatherers and the origins of religion. Human Nature, 27, 261-282. https://doi.org/10.1007/s12110-016-9260-0.',
      'IV. Omnism (1/1, Tripp)',
      'A. The recognition that wisdom, truth, and legitimacy both are and can be found in ALL spiritual paths.',
      'V. Panpsychism (1/1, Tripp)',
      'A. The philosophical view that consciousness is a fundamental and universal feature of reality, meaning that even basic physical entities like electrons have some form of mind or mind-like quality.',
      'VI. Pantheism (1/1, Tripp)',
      'A. A doctrine which identifies God with the universe, or regards the universe as a manifestation of God.',
      'VII. Hylozoism (1/1, Tripp)',
      'A. The philosophical doctrine that all matter is alive or animated, either in itself or through a world- soul',
      'VIII. Relational Theology:',
      'A. Process theology (1/1, Tripp)',
      '1. Alfred North Whitehead (Mathematician and philosopher)',
      'B. Open and Relational Theolog y (1/1, Tripp)',
      '1. God and creation engage in a dynamic, reciprocal relationship, contrasting with traditional views of a distant, unchanging God. This perspective emphasizes that God experiences time moment by moment and is genuinely affected by the world and the free choices of creatures.',
      '2. Includes process theology, but is not limited to it.',
      '3. Thomas Jay Oor d (Theologian and philosopher) (I will finish updating this soon) Philosophy',
      'I. General Philosophy',
      'A. The best choice to make as a human is to be the best person possible and try to leave the world a better place than you found it. (3/3, Rachel)',
      "B. Once a certain level of consciousness is reached, people have an obligation to personally try to make the world a better place. This doesn't have to be an all-consuming goal, but should be a goal in some manner. Part of how this should be done is by spreading the word about psychedelics and helping others obtain them if possible, especially once legal. It may not be great to condone or try to convince people they need to break the law. More thinking and discussion is required for this belief. (2.8/3, Rachel)",
      'C. Nobody deserves to be imprisoned for using substances, even those that are harmful. (3/3, Rachel)',
      'D. DMT and other substances can be used to treat addiction and other ailments. (3/3, Rachel)',
      'II. Quantum Mechanics (3/3, Rachel)',
      'A. The science of Quantum Mechanics and spirituality intercept and allow us to get a glimpse of reality and how it works.',
      'B. Here, we will write different theories and aspects of quantum mechanics and draw parallels to the spiritual beliefs of the ORG.',
      'C. All matter is both a particle and a wave',
      'D. Everything is energy',
      'III. The Uncertainty Principle',
      'A. "could explain how prayer and other indirect action can change the outcome of an event". (3/3, Rachel)',
      'B. "The awareness of something could cause it to change, even if it\'s just pure consciousness" (2/2, Rachel)',
      'Anonymous Beliefs Of Private Members',
      "I. I believe that we along with everything else are just parts of the universe (Source) experiencing itself. Our time here on Earth is a sacred thing, we experience joy, pain, love, sadness, anger, etc... The good and the bad are all parts of the natural harmonious balance of the universe. I believe that Psychedelics have always been a reminder of that. They've been used for thousands of years in sacrament and religion and the people of old knew something that we're just now starting to rediscover as a society. Our separation from our connection with the other and mother Gaia has led us astray. So many of us have been plagued by and consumed by the evils of the world. Source cannot accept you back when you die if you have done nothing but evil. The balance of the universe is controlled by Source not you. If Source were to accept too much of the wrong energy back into itself it would tip the balance of the universe and everything as we know it would collapse. So if you are filled with too much negative, hateful energy then when you die you must go through a cleansing process. If you fail this process you come back to Earth, the karmic playground for humans and must live life again. If you pass this cleansing process you have the opportunity to join The White Light or to go back to Earth and live again. Every figure and or profit who has walked this planet has figured this out in some form or another. Buddha, Jesus, Apollonius, Krishna, etc... You must look within yourself to learn inner transformation, compassion, and that sense of universal love. Psychedelics show us a glimpse of that, of the other, they remind us we are all one and connected. They remind us of that which we have forgotten so long ago and they show us the path to not only remembrance, but to growth and personal enlightenment so that when the time comes we are ready to go back to Source.",
    ],
  },
  {
    id: 'infrastructure',
    title: 'Infrastructure',
    subtitle:
      'Octagon temple concepts, locations, sketches, and building process notes.',
    lines: [
      'Infrastructure Introduction',
      'I. Due to the vision highlighted in About Us/Contact, we aim to build multiple Octagon- shaped spiritual temples and research centers throughout the World.',
      'A. Below are some examples of what these could one day look like:',
      'II. See the Table of Contents for specific locations',
      'III. Feel free to make your own Octagon images for various locations and insert them for the rest of us to consider!',
      'IV. Leave a comment on your favorite Octagon and we will keep the one with the most votes at the header of the ORG Home page.',
      'V. Blueprint Introduction 1',
      'Southwest Virginia 3',
      'Colorado 6',
      'Austin Texas 10',
      'Miami Florida (Or Other Aquatic Location) 11',
      'Asia 14',
      'Los Angeles 15',
      'San Francisco 15',
      'New York 15 Etc. 15',
      'Miscellaneous 16',
      'Sketches/Inspiration 17 Video of an octagon skyscraper: https://youtu.be/dD1TgznCsJQ 17',
      'A. A rough draft containing the finer details for the Octagon design.',
      '1. Building Materials & Techniques',
      '2. Interior Design',
      'B. We are especially seeking more help from entheogenic friendly folk with construction, engineering, and building design skills.',
      '1. A goal is to eventually have Octagons designed and built by a crew who all use entheogens.',
      'a) This can be done on site or offsite in design studios or homes.',
      'b) Safety',
      '(1) It should go without saying, but extra safety measures should be followed when allowing construction workers to enter altered states while on the job site.',
      'c) When will they be used?',
      '(1) Before their work is started:',
      '(a) The purpose of this is to provide each of them with visions and/or insight on how to do a better job with the next step of the building process.',
      '(2) After their work is completed:',
      '(a) The purpose of this is to provide each of them with visions and/or insight on how to better build the next Octagon based on additional realizations of mistakes made during the previous step.',
      'C. We will eventually post this to the website where members can vote on building decisions.',
      '1. Things such as colors, styles, locations, etc.',
      '2. In the meantime, voting can still be done in the pages document.',
      'Southwest Virginia',
      'Colorado',
    ],
  },
  {
    id: 'research',
    title: 'Research',
    subtitle:
      'Research ideas, study directions, methods, and spiritual science questions.',
    lines: [
      'Research',
      'Research Disclaimer: Any Of These Research Ideas With Human Participants Will Pass All Legal Requirements And Review Boards Before Their Initiation Note: Since previous studies have shown the high occurrence of spiritual visions from psychedelics, should future studies on general psychedelics be required (by review boards) to have informed consent from participants that they are okay with possibly having spiritual visions?',
      'I. We must eventually vote to decide what area(s) of research will be focused on in the first-built Octagon.',
      'A. I suspect this vote will be heavily influenced by a future funding where a philanthropist specifically requests that the money goes towards one area of research more than another.',
      '1. We would then need to decide whether we are willing to accept the funding if such stipulations exist.',
      'a) A good way to decide on this is to ask ourselves the following question: "Does this research improve the universe, and is there anything else The Universal Creator would want us to prioritize first?"',
      'B. One idea I have for this is to post our areas of research interest and then incorporate a way into the website that allows individuals to donate to each area, thus locking their money from going to other areas of research.',
      'II. Optimizing The Psychedelic "Set and Setting" As A Treatment For Substance Use Disorder (S UD) And Chemical Addictions',
      'A. Octagons specific to this will be built around the world.',
      '1. Designing these buildings to increase the likelihood of spiritual theophany is important, but should not be emphasized too much, or many people will refuse to come.',
      'a) I have met several people who specifically told me they refused treatment at " addiction centers" that pushed religion onto them.',
      '2. The first one will likely be mid-rise buildings and will be responsible for optimizing the method.',
      "a) From here, high-rise/skyscraper Octagons will be built with whatever further optimizations weren't yet possible. These will be specialized treatment facilit ies, likely built near major cit ies where the need is the greatest (such as SF, LA, or NYC). These could treat hundreds to thousands of people at once.",
      '3. They must be built in a way so that the building can be easily transitioned into other uses once the addiction problems have been reduced.',
      'a) An example of this is that the original mid-rise octagon meant for SUD treatment could be transitioned to treating non-chemical addictions (as soon as there is a high-rise SUD Treatment Octagon built for this group of people to go to).',
      '(1) From here, future changes could be made to the building plans of subsequent high- rise octagons, so that they are better suited for transitioning to non-chemical addictions (once they start running out of people who need SUD treatment).',
      '(2) Other subsequent transitions could be towards becoming education and integration centers for the homeless and recently released non-violent criminals.',
      '(a) Then, eventually, for violent criminals, (although this will obviously require much thought before it can be done with reasonable safety for staff).',
      '4. A balance of science and funding will determine:',
      'a) The number of floors and the width of each Octagon.',
      'b) The allocation of space dedicated to exercise, dining, education, etc?',
      'c) The duration that participants will (ideally) stay in the center before going home.',
      'd) To emphasize the education, I want to test a partnership with a community college so that people interested can start a higher education, while still at the ORG.',
      "B. I have a private document with much more on this, but it's so lengthy that it's probably best saved until it can have its own place on the website. Furthermore, I would like to sort through it all and change the order from chronological to importance.",
      'C. The entheogenic use of psychedelics should be welcomed and encouraged, but not required or coerced. Theophanys will come when they are ready.',
      'III. The Judeo-Christian Psychedelic Pilgrimage',
      'A. It is a life-goal of mine (Tripp) to get a large group of people together to take a few months to then travel to Egypt, and to follow the path highlighted in the Bible to the best of our ability.',
      '1. Along this path, we will stop as close as possible to locations of key biblical events. Here, we will use entheogens and record our visions with the utmost scientific rigor.',
      'a) ORG and/or an independent organization will use statistics to compare the visions from individuals or small groups of individuals, and provide us with a relative degree of confidence in the authenticity of the knowledge each vision shared. We will hopefully learn more about the Bible and any potential (intentional or unintentional) lies and/or other inaccuracies of the Biblical text.',
      'B. The biggest hurdle of this endeavor, I believe, will be getting the approval of all governments in these regions.',
      'C. Locations to visit:',
      '1. The Church of St Sergius in Cairo',
      'a) "Where the holy family is believed to have rested in Egypt (Matthew 2:13) after Joseph is warned by an angel in a dream to take Yeshua (Jesus) and Mary to Egypt to escape King Herod\'s wrath (see 3 on Map 4). They escape by night, just before Herod orders the murder of all baby boys born in and around Bethlehem during the last two years. " - https://thebiblejourney.org/biblejourney1/3-jesuss-childhood-journeys-b/the-holy- family-flee-to-egypt/',
      '(1) Some Brazilians believe that a DMT-containing drink was responsible for the visions and/or dreams that Joseph had.',
      '(a) "The plant itself (DMT-containing Mimosa Hostilis) is a representation within the Afro-Brazilian community, who believe that it was through Jurema that the Holy Family escaped Herod".',
      'i) Etnobot\u00e2nica Hist\u00f3rica da Jurema no Nordeste Brasileiro',
      '(1) https://www.researchgate.net/profile/Valeria-Dos-Santos-2/ publication/ 264880040_Etnobotanica_Historica_da_Jurema_no_Nordeste_Brasil eiro/links/55edb3e908aedecb68fb26a7/Etnobotanica-Historica-da- Jurema-no-Nordeste-Brasileiro.pdf',
      'b)',
      'D. We should contact Rabbi Harry Rozenberg because his organization owns farm land in Israel, and he may be able to help get this idea going.',
      'E. This can certainly be replicated for other religions/spiritualities as well.',
      'IV. The Underground Railroad Pilgrimage',
      'A. Similar to the Judeo-Christian Psychedelic Pilgrimage, we can visit sites that were related to The Underground Railroad and have visions that will show us secrets that were kept from the history books in order for The Underground Railroad to continue.',
      'B. MY BONDAGE and MY FREEDOM by FREDERICK DOUGLASS',
      '1. Written circa 1855',
      '2. Chapter 21?',
      'a) Frederick Douglass intentionally omits details of how he escaped (even writing the book 17 years after his escape).',
      "(1) The purpose of this was to help others continue escaping and to protect those who helped him escape, AND to protect those who didn't help but would still have been assumed, accused, and punished as such, even without proof.",
      '(a) This is similar to the underground " psychedelic" railroad and how much history has been lost due to the need to keep secrets to prevent prosecution/harm to others.',
      '3. Frederick Douglass National Historic Site, District of Columbia.',
      "4. There's also a mariner memorial in Baltimore, named in his honor.",
      'V. To See or Not to See? (Color Dominance of Entheogens/Psychedelics)',
      'A. To determine why certain colors are more or less dominant than others during visions, we could have Xpeople spend Yday(s) in a room of a single color. We would then move them to either a white or a black room and could then give medium doses of an entheogen and see what color(s) they report seeing, and rank each color with its respective order of dominance.',
      "1. I hypothesize that people will either see the same color as the room due to those neurons being primed (up-regulated) to activate again, OR they will see the opposite color being dominant due to the neurons of the previous room's color being depleted (down-regulated).",
      'B. A statistician would be needed to figure out what numbers are needed for Xand Y',
      'C. We would need to decide if people are allowed to choose their favorite color to spend their day(s) in, or if colors would be assigned randomly and thus risk some people dropping out of the study or having bad experiences because they were put into a room with their least favorite color.',
      '1. Either way, both could potentially skew the results.',
      'VI. Understanding Why DMT Dosed (Roughly) Once Per Hour Results In A "Reverse Tolerance" (RT)',
      'A. Effects get stronger with each dose, and thus, smaller doses are needed each hour to produce ideal breakthroughs.',
      '1. This allows for clearer visions and with fewer side effects, such as coughing from inhaling large amounts of often overly hot vapor.',
      'a) Note that too cool vapor can also irritate, as it will condense into solid particles within the throat.',
      '2. There may be a plateau dose where decreasing no longer applies.',
      'a) When I did this around the age of 20, I would space out my doses roughly like so (Numbers in mg): 30, 28, 26, 24, 22, and sometimes 30, 25, 20, 18,',
      '18. But I did not experiment with this method often enough, nor do I have access to a scale accurate enough to make any substantial claim about what detrimental dosing protocol is best.',
      'B. As far as I/we know, this applies to the vapor ROA only.',
      '1. It might apply to other ROAs, though the ideal time between doses could be different.',
      '2. Important note here is that if DMT vapor is inhaled within the ~3-15 minute (maybe ~5-45 minute) range, then a traditional tolerance (TT) will occur, as well as often a headache.',
      'C. Causes of the RT might be',
      '1. Long-term potentiation (LTP) of neurons in <1h',
      'a) What is the time needed for LTP to peak?',
      '(1) In about 30 minutes following the induction of LTP, the actin-spine architecture is essentially destroyed and then rebuilt into an enlarged stable spine that will help provide resistance to endocytotic processes.',
      'b) How long does LTP last?',
      'c) What downstream proteins impact LTP around 1 hour (either up- or down-regulated) that have returned to normal levels around 2-3 or even 24 hours?',
      '(1) The time frame here has not been tested. I know that effects are amplified around 1 hour and that the effects around 24 hours are not amplified, but a solid study should be completed that shows the intensity drop off of DMT vapor sessions spaced 30 minutes, 1 hour, 2 hours, and 3 hours apart. From this study, we will see if more time is needed to offer a full " reset" of intensity to baseline.',
      '(2) Many protein changes persist for days after the administration of a drug. These would not be involved here.',
      'd) What secondary messengers are involved with DMT receptors?',
      '(1) (Both internal and externalized 5-HT and other receptors, TAAR, S1R, etc.)',
      '2. Secondary, tertiary, etc., compartments based on pharmacokinetic models.',
      'a) Deeper brain regions.',
      '(1) Downstream release of other NTs caused by the release of the initial DMT/5HTR signaling.',
      "b) DMT enters through passive diffusion into the postsynaptic neuron (David Olson Lab, 5- HT doesn't do this, because 5-HT is too polar).",
      '(1) Is this required for the psychedelic effects?',
      '(2) How much DMT is left inside the neuron at sub-perceptual levels around the 1hr point?',
      '(3) Once inside the postsynaptic neuron, DMT can bind to internalized 5-HTRs, and from here, the effects are relatively unknown.',
      '3. There are likely many more things to consider, as well as considering what mechanisms might be working in opposition to the LTP and would thus be responsible for the TT seen in the <45minute range.',
      'VII. Visual Frequencies',
      'A. Are the visions from entheogens matching the frequency of action potentials in the visual cortex?',
      'B. Idea influenced by this video',
      '1. https://www.facebook.com/share/r/17bebN4KQZ/?mibextid=wwXIfr',
      'VIII. Food Cultivation for Mars and Beyond',
      "A. It is my intention for each Octagon to have greenhouses and/or indoor hydroponic facilities where people can learn to grow food, as well as supply each Octagon with fresh food grown on site, but the research side here would be more focused on hydroponics/aeroponics and other techniques required to grow food outside of Earth's boundaries.",
      'IX. Theophany or Theo-" phony"?',
      'A. We should develop a study to test and determine why most people are more likely to have theophany from psychedelics, while some people report no spiritual insights, even with many breakthrough experiences.',
      '1. Hypothesis:',
      'a) Their reported " breakthroughs" aren\'t actually breakthroughs.',
      'b) They are devout atheists to begin with.',
      "c) There's a genetic explanation (like a different ratio of all the known psychedelic-binding receptors).",
      'X. Drunk vs. Psychedelic Driving (Crashes and Fatalities)',
      'A. As a result of drunk driving, ethanol kills many more people than just those who use it.',
      'B. I am unaware of any crash caused by psychedelics, though no doubt they happen. I would like to see a study done to determine what percentage of people drive on psychedelics compared to those who drive on ethanol.',
      'C. A second part of this study would be to compare statistics for those who do drive and see which of the two groups is more likely to crash.',
      'D. A third part would be to determine the severity of the crashes and which are most likely to result in fatalities.',
      "E. I imagine it's a much lower percentage of people who drive, crash, and kill others while using psychedelics compared to ethanol.",
      '1. This is because most people who use psychedelics are cognizant enough NOT to drive, and those who do, usually only do so after the peak effects are gone, and even if some geometric visions remain, they are not impaired, and their reflexes are not delayed.',
    ],
  },
  {
    id: 'legal',
    title: 'Legal',
    subtitle:
      'Legal references, attorneys, risks, recommendations, and archive notes.',
    lines: [
      'Legal',
      'I. 508(c)(1)(A) religious/spiritual organization /church',
      'A. Registered with the state of VA',
      'B. In Church of Eternal Life and Liberty, Inc. v. Commissioner, 86 T.C. 916, 924 (1986), the Tax Court defined a church, for IRC 170(b)(1)(A)(i) purposes, as " a coherent group of individuals and families that join together to accomplish the religious purposes of mutually held beliefs."',
      '1. https://www.irs.gov/pub/irs-tege/eotopica94.pdf',
      'II. 501(c)(3) non-profit',
      'A. We are filed as a church with the IRS, but we still need to complete filing additional materials before we receive 501(c)(3) tax-exempt status.',
      '1. Employer Identification Number: 33-3400742',
      'III. The use of the word spiritual and all words which are derivatives of it is/are considered by The ORG to be synonymous with religious and all words which are equal derivatives of it (unless specifically stated).',
      'A. Spirituality = Religion',
      'B. Spiritual = Religious',
      'C. Etc.',
      'IV. Spiritual Text',
      'A. It should be noted that our official texts shall always reside in a digital form.',
      '1. This is the best way to ensure they can be rapidly and effeciently updated, as well as for important parts to be easily searched for and located.',
      '2. If our documents are ever presented in a courtroom, they should be done so in their digital form.',
      '3. There is nothing wrong about printing our texts on paper, BUT they can no longer be considered official or up-to-date.',
      'a) It is recommended that printed forms of the documents include a link so that the reader can easily locate the updated form online. We will work towards adding these links to all our documents once the website has been established.',
      'V. Member Privacy and Protection',
      'A. We will never share member information with the government.',
      "B. First Choice Women's Resource Centers, Inc. v. Davenport (4/29/2026)",
      '1. A 2026 Supreme Court case where the Court ruled that a subpoena demanding donor information from a nonprofit organization violated its First Amendment rights, establishing that such demands can cause injury even before enforcement. The unanimous decision emphasized the importance of protecting associational rights and privacy for organizations engaged in advocacy.',
      "2. Bridger Lee Jenson's Bullet Points from this case (with respect to Singularism and other entheo organizations):",
      'a) Shields our members and our donors identitites from government demands.',
      'b) Protects minority religions',
      'c) Reinforces our right to challenge the government targeting in federal court immediately.',
      'd) Blocks the government defense of " we will keep your list confidential".',
      'e) Broad unanimous backing from the federal courts.',
      'f) Source: Watch 32:20-33:45 here: https://www.facebook.com/share/v/ 14YHgBLfnyJ/',
      'VI. Entheogenic Lawyers',
      'A. Highly Recommended',
      '1. George "Greg" Lake',
      'a) TX but collaborates in all states',
      '2. Tarin',
      'S. Hale',
      'a) OH, but collaborates in all states',
      '3. Jerry',
      'D. Patchin',
      'a) His early work with the NAC led to the formation of the Federal Religious Freedom and Restoration Act (RFRA) in',
      '1993.',
      'b) From 1999 to 2006, he helped with the UDV ayahuasca case',
      '(1) Gonzales v. Uniao do Vegetal, 546 US 418',
      '(2006)',
      'c) Formerly counsel and a founding Director of the Heffter Research Institute',
      'd) You can read more about him at',
      '(1) Wasiwaska',
      '(2) Texas Bar',
      'e) He deserves most of the credit for strengthening/defining our religious freedoms',
      'f) He is nearly retired but still works primarily for the NAC.',
      "g) He isn't currently taking cases for non-NAC entheogenic organizations (due to conflicts of interest)",
      'h) Despite the above, he can be reached at +1',
      '(713) 408-9090 and certainly seemed to appreciate my call, in which I thanked him for the work he has done.',
      "4. Entheo Community's Lawyer List",
      'a) Highlights from this list (not already mentioned above)',
      '(1) ANTITHESIS *',
      '(a) "We help clients navigate the complex patchwork of federal and state laws relating to psychedelics".',
      '(b) "We are proud advocates for the causes, and movements that influence social progress" and sometimes do pro bono work.',
      '(c) CA, CO, IL, DC',
      '5. Top 200 Global Psychedelic Lawyers and Policy & Regulatory Experts Guide',
      '6. Psychedelic Bar Association',
      "7. Jonathan 'John'",
      'M. Arthur, Esq.',
      'a) Virginia Litigation Attorney in Richmond, VA',
      '(1) Has done lots of Civil Rights cases. Also, criminal defense and constitutional law.',
      "b) Although he doesn't specialize in entheogenic law, he is very knowledgeable about entheogens. He is also the most knowledgeable (and sympathetic) civil rights attorney whom I have had the pleasure of speaking with.",
      'c) Contact Info: 804-783-2000 and maybe 804-991-4308',
      '(d)',
      'd) Suggested to me by Robert Canard',
      '8. Radical',
      'a) Entheogenic Churches AND Crypto',
      'b) CA and NY',
      'c) New to ORG, but they are worth looking into.',
      'B. NOT Recommended',
      '1. Robert Rush',
      'a) Is known to have failed to honor attorney-client confidentiality and has disrespected the religious beliefs of clients. He has also (on three separate occasions) talked badly about another attorney and asked me " not to tell the other attorney".',
      'VII. ORG Archive',
      'A. Older files that have now been phased out',
    ],
  },
  {
    id: 'future',
    title: 'Future Ideas',
    subtitle:
      'Future website, app, invention, and experience concepts for ORG.',
    lines: [
      'Future Ideas Please vote on which idea is your favorite and we will re-arrange the ideas in order of most interest.',
      'I. The Inn Be-Twain Submarine',
      'A.',
      'B. A massive (bigger than above), yellow-painted submersible cruise ship that is a luxurious and fun vacation for fans of The Beatles, Ma r k Twain, and more. All of w hom, it will give homage to.',
      '1. The income made from the vacationers would be used to fund a smaller submarine which would be capable of diving deeper and doing the bulk of the research.',
      'a) This smaller submarine (or many of them) would ideally be able to be released from the cruiser. This would allow vacationers the option of the additional activity of diving deeper and participating in the collection of samples, etc.',
      'C. The reason for the name:',
      '1. During a high-dose LSD experience (circa 2018), I was shown that psychedelics were " in betweeners". The idea of The Inn Be-Twain Submarine was conceived years later, after many thoughts which built onto the initial trip.',
      '2. The experience:',
      'a) 45 or so minutes into to experience, a song arose that was fast paced and high pitched. The LSD sung to (and through) me about the problems of stimulants, then the song slowwed wayyyyy down, the voice deepened and began singing about the problems of sedatives. Finally it finished with the most beautiful part of the song. The speed and pitch returned to normal and it highlighted psychedelics for being " in between" the extremes.',
      '(1) Th is was in my first few weeks of sobriety from stimulants, which I blame for hindering my ability to remember most of the verses...',
      'b) Unsurprisingly, there were dance moves too. The stimulant part made a sickening reference to the Nazi salute (in reference to their use of amphetamines) but the " in-between" psychedelic hand motions were of a gentle flowing wave. I can\'t remember what motion was made during the sedative part but it was the most wild thing. I could feel the effects of each other drug despite having only taken LSD and been weeks clean from stimulants and having hardly touched opioids about a year before.',
      'c) When the time is right, I am certain the vibes of this trip will make their way to someone who can actually replicate it professionally.',
      '3. Psychedelics are also called " all-rounders" opposed to the uppers and the downers.',
      '(1) The earliest evidence of "all a-rounders" being used to describe psychedelics is in the 1978 movie Up in Smoke by Cheech and Chong.',
      '(a) I learned this from a podcast interview with Dr. Matthew Johnson.',
      '4. In is spelled Inn, (in the name), because it will be an Inn.',
      '5. Between is spelled Be-Twain to honor Mark Twain.',
      'a) Best known for his literature and for his role as a steamboat captain, he was also a prominent abolitionist and friend of Frederick Douglas, despite Mark Twain having originated from a slave owning family.',
      '6. Submarine should be pronounced (sub-mar-ane), so that it rhymes.',
      'D. Other Info',
      '1. Food menu and other bits of literature would be Mark Twain themed and music would primarily be the Beatles and others from the era.',
      '2. Lots of unexplored territory in the ocean floor. Lots of medicinal plants/life. Lots of environmental harms to be reversed. Lots of lots more.',
      '3. Mark Twain quotes',
      'a) "Humor is tragedy plus time"',
      'b) from The Mysterious Stranger and Other Stories',
      '(1) "There has never been a just [war], never an honorable one--on the part of the instigator of the war. I can see a million years ahead, and this rule will never change in so many as half a dozen instances. The loud little handful--as usual--will shout for the war. The pulpit will--warily and cautiously--object-- at first; the great, big, dull bulk of the nation will rub its sleepy eyes and try to make out why there should be a war, and will say, earnestly and indignantly, \'It is unjust and dishonorable, and there is no necessity for it.\' Then the handful will shout louder. A few fair men on the other side will argue and reason against the war with speech and pen, and at first will have a hearing and be applauded; but it will not last long; those others will outshout them, and presently the anti-war audiences will thin out and lose popularity. Before long you will see this curious thing: the speakers stoned from the platform, and free speech strangled by hordes of furious men who in their secret hearts are still at one with those stoned speakers--as earlier--but do not dare say so. And now the whole nation--pulpit and all--will take up the war-cry, and shout itself hoarse, and mob any honest man who ventures to open his mouth; and presently such mouths will cease to open. Next the statesmen will invent cheap lies, putting the blame upon the nation that is attacked, and every man will be glad of those conscience-soothing falsities, and will diligently study them, and refuse to examine any refutations of them; and thus he will by and by convince himself the war is just, and will thank God for the better sleep he enjoys after this process of grotesque self-deception."',
      'II. The Vitruvian Shower',
      'A. AI really struggled to come up with any image that closely resembles this idea, but the above is acceptable. The arms should be recessed into the wall, the shower itself should be more recessed and have a door that closes on it to retain heat. The door could be glass or stainless steel (and include more nozzles and scrubbing pads on it).',
      'B. An idea that (obviously) originated from shower thoughts',
      'C. The high pressure sprayer nozzles and scrubbing pads should automatically form to the height, width, etc. of the users body.',
      'D. The device will then soap/scrub body, face, and hair. Front and back at the same time.',
      'E. A full shower could be completed in 1-2 minutes',
      'F. It will revolutionize the world by saving time similar to the clothes washing machine, lawnmower, dishwasher, robot vacuum, etc.',
      "G. The name is an ode to Leonardo da Vinci's Vitruvian Man and his drawing was an ode to Vitruvius who is known for his book De A rchitectura, which I listened to an audiobook summary of.",
      '1. From Grok 3: One of his most well-known contributions is the concept of the "Vitruvian Man," which describes the ideal human proportions and their relation to architectural design-later famously illustrated by da Vinci. Vitruvius argued that buildings should embody three qualities: strength (firmitas), utility (utilitas), and beauty (venustas), a triad that remains a cornerstone of architectural theory.',
      'H. Prior to any of this, one of my favorite early DMT (vapor) visions included a 3D spinning Vitruvian man which gave me insights into something significant that I am not yet comfortable typing.',
      'I. The t emperature of water should be adjustable digitally and in at minimum 1/10th degree Celsius or half degree Fahrenheit increments. Maybe even consider the option to have a temperature gradient for people who want their pores opened for the washing and then closed as they exit.',
      'J. The shower needs a way to prevent people from being sprayed with cold water as it starts. So either have a way to cycle hot water through it or have it purge before accepting the human body into its form.',
      'III. Onco Jeans',
      'A. A clothing line for jeans where 100% of the profits go to funding cancer research.',
      'B. A play on words of " oncogenes"',
      'C. Consider partnering with one of these USA brands:',
      '1. https://dearborndenim.us/pages/contact-us',
      '2. https://toddshelton.com/blog/about-todd-shelton/made-in-america/best-jeans-made- in-usa? srsltid=AfmBOork06gymoLb8KsiRE-4tAAcA7CcCRYDHgl0UJpoqlovxc6uZj21',
      '3. https://www.thegoodtrade.com/features/american-made-denim/',
      '4. https://www.stillmadeinusa.com/jeans.htm',
      'IV. Redneck Recycling Range (RRR)',
      'A. A shooting range meant to encourage folks to recycle their glass, plastic, and aluminum bottles, cans, etc.',
      '1. This idea came to me from a collection of adolescent memories, as well as seeing empty beer bottles and cans disposed of alongside the road on family property in the small rural Giles County, VA.',
      'B. The shotgun range will have an air-powered beer bottle-launcher (potato gun style cannon) that shoots bottles (with or without) water in them for folks to then shoot and shatter. The broken glass will fall onto a bed of concrete, and then every so often, a mechanism will collect the broken glass into a recycling bin for transport to a facility.',
      '1. The added benefit of the glass being shattered is that more glass can fit in a container, thus allowing for more efficient transportation via larger mass per container hauled or smaller container sizes used (if there is a maximum weight limit).',
      'C. Rifle and pistol ranges could handle aluminum and plastic bottles',
      'D. All shell casings could also be recycled.',
      'E. A rough sketch',
      '1.',
      'F. Credit goes to my uncle, Mark Zunk, for the idea of sloping the concrete pad to reduce the need for a conveyor belt or second sweeper.',
      'G. Adam Pearman from Giles, VA is to thank for mentioning concerns of lead shot contaminating the glass, therefore, requiring the use of steel shot will likely be more cost effective when compared to the cost of separating the glass from the lead. The RRR could also require people to use ammo purchased at the facility that way no lead shot was accidentally (or intentionally) used. The goal here would be to buy steel shot in bulk and to be able to offer it to shooters at a price that is competitive with lead shot. This would be done either at-cost or above cost as part of the necessary steps to make the RRR financially feasible, especially in the beginning.',
      'H. Other notes:',
      '1. Broom bars would need to raise and return to starting point like a bowling ball sweeper.',
      'V. Autonomous Off-road Amusement Park Ride (we need a better name)',
      'A. This is certainly one of my less practical ideas, but it could help to bring in funding for some of the other ideas that benefit humanity in more useful ways.',
      "B. The idea originally came from thinking of having an ORG Octagon built in the woods of my family's land with the main purpose of treat ing substance use disorder. I was trying to think of fun (adrenaline and dopaminergic) activities that could be done outside (on the land that wasn't wooded) and that would distract those from their cravings.",
      'C. Modify a Tesla Cybertruck platform',
      '1. Suspensio n, tires, roll cage, etc.',
      '2. Full body harnesses for 4 people.',
      '3. Remove steering wheel and pedals so that autopilot with additional cameras/sensors are the only option for controls.',
      '4. Build a dirt track with lots of jumps.',
      '5. Put sensors throughout the track that monitor the humidity and temperature of the soil.',
      '6. Connect the autopilot computer to these sensors.',
      '7. Put four weighted crash dummies in the vehicle.',
      '8. Program it to d rive around the track and record data while increasing the speed each lap.',
      '9. Use the brakes/acceleration to raise/lower the vehicle nose and perform flips, while computer learns how to predict the best landing angle with on board sensors',
      '10. Make the jumps as high as possible, and the speed as fast as possible, while still in safe limits. Using the same statistical P value that is required for amusement park rides.',
      '11. Determine a safe protocol for when to replace parts long before they risk breaking.',
      '12. Other people that might be interested',
      'a) @Teslarati @TeslaMotorsClub @steveo @XGames @redbullmotors @redbull @axell_hodges @MonsterEnergy',
      'b) mxtrackbuilders.com or @track_solutions on instagram for building the track',
    ],
  },
  {
    id: 'donations',
    title: 'Offerings',
    subtitle:
      'Gifts from ORG, recommended donation values, allocations, and contribution notes.',
    lines: [
      "Gifts and Contributions Gifts (From ORG) - These are items that ORG offers to our members regardless of whether they can afford them or not. - For each item, we will include The Price ORG Pays (TPOP) and/or the cost of materials or time that ORG spent to acquire it. - If you know a cheaper or higher quality source for any of our gifts, contact us, as we will make our best effort to incorporate the new source into our gift options. - By making these free, we generally ask for pure-hearted donations of at least 20% more, plus $15 to cover the shipping, to continue allowing us to offer these. - The 20% rule doesn't work well for certain items (like 1 tab of LSD), where 20% more than a $3 tab is only $3.60. This would not cover our time to pay staff to package and mail the gift. - For this reason, and due to frequent requests, we will include Recommended Minimum Donation (RMD) values for most items. - Part of our faith is the belief that we will continue to be provided for financially, in a way that allows us to achieve the growth needed to accomplish our larger goals, whilst also sharing entheogens and other gifts with those who can't easily afford them.",
      'I. Entheogens',
      "A. The sharing of sacraments is currently on pause while we navigate the legal aspects of it, but below is what it will look like when we can resume: (many of these numbers are guesses, as we haven't spent time sourcing in quite a while).",
      'B. DMT',
      '1. Forms:',
      'a) Freebase',
      '(1) TPOP: $60/g or $15/g + ~5 days of labor for x grams.',
      '(2) RMD: $100/g',
      'b) Fumarate',
      '(1) TPOP: $80/g or $16/g + ~6 days of labor for x grams.',
      '(2) RMD: $120/g',
      'C. LSD',
      '1. TPOP:',
      '2. RMD:',
      'D. Psilocybin Mushrooms',
      '1. Variety A',
      'a) TPOP:',
      'b) RMD:',
      '2. Variety B',
      'a) TPOP:',
      'b) RMD:',
      'E. 4-AcO-DMT',
      '1. TPOP:',
      '2. RMD:',
      'F. Mescaline',
      '1. TPOP:',
      '2. RMD:',
      'G. MDMA',
      '1. TPOP:',
      '2. RMD:',
      'H. MDA',
      '1. TPOP:',
      '2. RMD:',
      'I. 2C-B',
      '1. TPOP:',
      '2. RMD:',
      'J. ETC',
      "1. If you have a source for an entheogen that isn't on this list, let us know!",
      'II. 3D Printed Objects',
      'A. Entheogenic Molecules',
      '1. Sizes range from ~5cm all the way to 25.6cm on the longest size of the molecule',
      '2. Shown below are DMT molecules: a 10cm in cyan/seafoam green and a 12cm in white (that glows white). 15cm, 10cm, 8cm DMT Molecules + #000, #0 Capsule Cones + RTA Coil Cutting Tools',
      '3. Any molecule can be printed, but we have only printed DMT and Ketamine so far.',
      'a) We welcome the challenge to do more complicated molecules like THC and LSD.',
      "4. RMD's",
      'a) DMT',
      '(1) 8.37cm',
      '(a) $25 (high-quality, 0.2mm nozzle)',
      '(b) $50-100 (Ultra-fine quality, slower printing speed)',
      '(2) 10cm',
      '(a) $15 (standard quality, 0.4mm nozzle)',
      '(3) 15cm',
      '(a) $30 (standard quality, 0.4mm nozzle)',
      '(b) $20 (Medium-low quality, 0.6mm nozzle)',
      '(c) $10 (low quality, 0.6mm, faster printing speed)',
      '(4) 25.5cm',
      '(a) $45 (Medium quality, 0.6mm nozzle)',
      'b) Ketamine',
      '(1) 10cm = Ask if interested, but ~$15-20 off my memory.',
      'B. Octagonal Cones',
      '1. Used for easy and accurate weighing of a 510-style atomizer before/after dosing.',
      'a) The old style was a circular cone with a hole size slightly larger than the 510 threading.',
      '2. Sizing: Any size can be custom-made, but we currently have (Width x Height in mm)',
      'a) 40x5',
      'b) 40x7',
      'c) 40x15',
      'd) 40x20',
      '3. Inserts',
      'a) "Capsule Cone"',
      '(1) Perfect for accurately weighing individual capsules.',
      '(2) Any-size cone can be made to fit any common-size capsule.',
      '(3) Older Style (#0 and #3 sizes):',
      '(4) We are working on designing a top and bottom that will fit seamlessly together (and be clear/see-through) with the intention of it looking like an octagonal hourglass with " sand" flowing through it.',
      '(a) One of my early theophanies was of an hourglass. If interested, you can read about it when the Theophanies page goes public.',
      'b) "Display".',
      '(1) Made to display 510-sized atomizers (threaded)',
      '(2) Can be placed on a shelf and gives the option to slide the 510 atomizer across the table without worry of the atomizer tipping over (think of a shot glass being slid down a bar).',
      '(3) Old style had the 510 letters on a circular disk, which was less attractive, IMO.',
      'C. Drip Tips',
      '1. Mainly for RTAs, but they can still be useful with RDAs',
      '2. We currently have 810 and 510 sizes, with an optional anti-spitback corkscrew (zoom in on the purple tip below). These are all made of food-safe PETG and are resistant to water and white vinegar. This means that any DMT stuck inside of them can be recovered by washing them out with vinegar and then re-extracting from it like any A/B tek, or by adding the vinegar DMT to the next extraction. RMD = $10 for one and $15 for two.',
      '3. We also have glass drip tips',
      'a) 810/510 interchangeable with custom-cut SS316 anti-spitback mesh inserts.',
      '(1) RMD = $10 (Top two and right)',
      'b) 810 straight tube, easier to clean, but no option for a flat mesh insert.',
      '(1) RMD = $5 (bottom left)',
      'D. 810 Plug for RTA/ RDA/E-Mesh',
      '1. Reduces the chance of oxidation of DMT on a wick, as well as keeps out any debris (dust, sand, dirt, etc.). Great for taking a device to the lake, hiking, etc.',
      '2. IMAGE',
      'E. Mesh Template Tool',
      '1. Made for quickly sizing and cutting SS316 Mesh on a 90 \u00b0.',
      '2. Any length is possible, but I currently prefer 16mm with the Hadron (Dual) Mesh',
      '3. To use the tool, the print should be raised a few mm above (in the pictures) so that the width of the print is equal to the width of the mesh, then with the long end flush on one side, the mesh should be folded over the flat/designed side (carbon fiber in this picture), and cut with a coil cutting tool (or sharp scissors).',
      'F. RTA Cutting Tool',
      '1. One large piece with multiple sizes, or smaller pieces with select or individual sizes.',
      '2. Using a second color for the numbering greatly increases the cost to ORG, due to the longer printing time required to flush out the previous color during every layer of printing.',
      'G. Colors (for any 3D print)',
      '1. Any color is possible; we recommend you search Amazon for your favorite color, followed by "3D printer filament" to choose.',
      'a) Note: Glow-in-the-dark and fading/changing colors are available, too.',
      'H. Designs (for the bottom of any flat-bottomed 3D print)',
      '1. Carbon Fiber, Diamond, Galaxy, and Starry:',
      'III. Blotter Art (Inactive)',
      'A. These are not yet ready for release and were a misprint.',
      'B.',
      '1. We need a way to ID them before sharing, in order to allow others to prove their authenticity in the future. Contributions/Donations (To ORG)',
      'I. If you would like to donate to help fund ORG, please send it to one of the following, and include a memo of " ORG donation":',
      'A. Cashapp',
      '1. $trippaardema',
      'B. Paypal',
      '1. @trippaardema',
      'C. Venmo',
      '1. @the_org',
      'D. Cash or cryptocurrency',
      '1. Reach out to Tripp through your preferred messaging app.',
      'II. You can also choose to include a memo that will signify your donation to be used towards a specific area, examples are:',
      'A. The Website',
      '1. This is important because getting a website established will be the best way to bring awareness to and grow The ORG',
      'B. Civil Law Suit/Legal Fund',
      "1. This is important because filing a civil suit against the government is also an important step toward growing The ORG, as many people are currently hesitant to contribute due to their lack of knowledge about what is and isn't legal regarding entheogenic spirituality.",
      '2. Per Greg Lake (https://www.patreon.com/posts/140450940? utm_campaign=postshare_fan)',
      'a) "Church of the Eagle and Condor requested $2,149,496.30 in attorney fees" for their civil suit.',
      'b) "CHLQ/Santo Daime requested $1,170,000 in attorney fees".',
      'c) "I have heard some lawyers are charging approximately 50K as just an initial retainer" (for filing the DEA exemption).',
      'C. Entheogens/Sacraments: synthesis, growing, acquiring.',
      'D. Octagon Infrastructure',
      'E. Individual Members:',
      "1. If you include an individual member's name on the memo, then you are trusting that member to make the decision of where the allocation of funds must go (these funds do not go to this member directly).",
      'F. Etc.',
      'III. Donations are tax-deductible',
      'A. This applies to 508(c)(1)(A) and 501(c)(3) organizations, and we chose to register as a 501(c)(3) to reduce the burden for those who, in the rare instance, may be audited and would otherwise have to prove the 508(c)(1)(A) sincerity on their own accord.',
      'IV. Non-monetary donations',
      'A. We must accept these as well.',
      '1. I (Tripp) once had an entheogenic organization co-founder accept my offering of a DMT molecule bookshelf. Then, after bringing it inside the building, a separate co- founder denied the gift, thus making me return it to the car.',
      'a) The second co-founder\'s excuse was that the organization " did not accept gifts," which was a flat-out lie, as they had accepted gifts before this, and they continued to publicly accept gifts afterwards.',
      'b) Evoking similar disheartening experiences should be avoided. Notes: We should look into using Zeffy as a free mailing and fundraising/donation platform...',
    ],
  },
] as const satisfies ReadonlyArray<ReferencePageContent>
