/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as GiftsContributionsRouteImport } from './routes/gifts-contributions'
import { Route as FutureIdeasRouteImport } from './routes/future-ideas'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BeliefsRouteImport } from './routes/beliefs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as OfferingsCheckoutRouteImport } from './routes/offerings.checkout'
import { Route as Archive5RouteImport } from './routes/archive/5'
import { Route as Archive4RouteImport } from './routes/archive/4'
import { Route as Archive3RouteImport } from './routes/archive/3'
import { Route as Archive2RouteImport } from './routes/archive/2'
import { Route as Archive1RouteImport } from './routes/archive/1'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsContributionsRoute = GiftsContributionsRouteImport.update({
  id: '/gifts-contributions',
  path: '/gifts-contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureIdeasRoute = FutureIdeasRouteImport.update({
  id: '/future-ideas',
  path: '/future-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BeliefsRoute = BeliefsRouteImport.update({
  id: '/beliefs',
  path: '/beliefs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsCheckoutRoute = OfferingsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => OfferingsRoute,
} as any)
const Archive5Route = Archive5RouteImport.update({
  id: '/archive/5',
  path: '/archive/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive4Route = Archive4RouteImport.update({
  id: '/archive/4',
  path: '/archive/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive3Route = Archive3RouteImport.update({
  id: '/archive/3',
  path: '/archive/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive2Route = Archive2RouteImport.update({
  id: '/archive/2',
  path: '/archive/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive1Route = Archive1RouteImport.update({
  id: '/archive/1',
  path: '/archive/1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/future-ideas': typeof FutureIdeasRoute
  '/gifts-contributions': typeof GiftsContributionsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/offerings': typeof OfferingsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
  '/offerings/checkout': typeof OfferingsCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/future-ideas': typeof FutureIdeasRoute
  '/gifts-contributions': typeof GiftsContributionsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/offerings': typeof OfferingsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
  '/offerings/checkout': typeof OfferingsCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beliefs': typeof BeliefsRoute
  '/community': typeof CommunityRoute
  '/future-ideas': typeof FutureIdeasRoute
  '/gifts-contributions': typeof GiftsContributionsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/offerings': typeof OfferingsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/research': typeof ResearchRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
  '/offerings/checkout': typeof OfferingsCheckoutRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beliefs'
    | '/community'
    | '/future-ideas'
    | '/gifts-contributions'
    | '/infrastructure'
    | '/join'
    | '/legal'
    | '/offerings'
    | '/profile'
    | '/research'
    | '/admin/orders'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
    | '/offerings/checkout'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beliefs'
    | '/community'
    | '/future-ideas'
    | '/gifts-contributions'
    | '/infrastructure'
    | '/join'
    | '/legal'
    | '/offerings'
    | '/profile'
    | '/research'
    | '/admin/orders'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
    | '/offerings/checkout'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beliefs'
    | '/community'
    | '/future-ideas'
    | '/gifts-contributions'
    | '/infrastructure'
    | '/join'
    | '/legal'
    | '/offerings'
    | '/profile'
    | '/research'
    | '/admin/orders'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
    | '/offerings/checkout'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeliefsRoute: typeof BeliefsRoute
  CommunityRoute: typeof CommunityRoute
  FutureIdeasRoute: typeof FutureIdeasRoute
  GiftsContributionsRoute: typeof GiftsContributionsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRoute
  OfferingsRoute: typeof OfferingsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResearchRoute: typeof ResearchRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  Archive1Route: typeof Archive1Route
  Archive2Route: typeof Archive2Route
  Archive3Route: typeof Archive3Route
  Archive4Route: typeof Archive4Route
  Archive5Route: typeof Archive5Route
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts-contributions': {
      id: '/gifts-contributions'
      path: '/gifts-contributions'
      fullPath: '/gifts-contributions'
      preLoaderRoute: typeof GiftsContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-ideas': {
      id: '/future-ideas'
      path: '/future-ideas'
      fullPath: '/future-ideas'
      preLoaderRoute: typeof FutureIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beliefs': {
      id: '/beliefs'
      path: '/beliefs'
      fullPath: '/beliefs'
      preLoaderRoute: typeof BeliefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings/checkout': {
      id: '/offerings/checkout'
      path: '/checkout'
      fullPath: '/offerings/checkout'
      preLoaderRoute: typeof OfferingsCheckoutRouteImport
      parentRoute: typeof OfferingsRoute
    }
    '/archive/5': {
      id: '/archive/5'
      path: '/archive/5'
      fullPath: '/archive/5'
      preLoaderRoute: typeof Archive5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/4': {
      id: '/archive/4'
      path: '/archive/4'
      fullPath: '/archive/4'
      preLoaderRoute: typeof Archive4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/3': {
      id: '/archive/3'
      path: '/archive/3'
      fullPath: '/archive/3'
      preLoaderRoute: typeof Archive3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/2': {
      id: '/archive/2'
      path: '/archive/2'
      fullPath: '/archive/2'
      preLoaderRoute: typeof Archive2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/1': {
      id: '/archive/1'
      path: '/archive/1'
      fullPath: '/archive/1'
      preLoaderRoute: typeof Archive1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfferingsRouteChildren {
  OfferingsCheckoutRoute: typeof OfferingsCheckoutRoute
}

const OfferingsRouteChildren: OfferingsRouteChildren = {
  OfferingsCheckoutRoute: OfferingsCheckoutRoute,
}

const OfferingsRouteWithChildren = OfferingsRoute._addFileChildren(
  OfferingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeliefsRoute: BeliefsRoute,
  CommunityRoute: CommunityRoute,
  FutureIdeasRoute: FutureIdeasRoute,
  GiftsContributionsRoute: GiftsContributionsRoute,
  InfrastructureRoute: InfrastructureRoute,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRoute,
  OfferingsRoute: OfferingsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResearchRoute: ResearchRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  Archive1Route: Archive1Route,
  Archive2Route: Archive2Route,
  Archive3Route: Archive3Route,
  Archive4Route: Archive4Route,
  Archive5Route: Archive5Route,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
