/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Archive5RouteImport } from './routes/archive/5'
import { Route as Archive4RouteImport } from './routes/archive/4'
import { Route as Archive3RouteImport } from './routes/archive/3'
import { Route as Archive2RouteImport } from './routes/archive/2'
import { Route as Archive1RouteImport } from './routes/archive/1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive5Route = Archive5RouteImport.update({
  id: '/archive/5',
  path: '/archive/5',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive4Route = Archive4RouteImport.update({
  id: '/archive/4',
  path: '/archive/4',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive3Route = Archive3RouteImport.update({
  id: '/archive/3',
  path: '/archive/3',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive2Route = Archive2RouteImport.update({
  id: '/archive/2',
  path: '/archive/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Archive1Route = Archive1RouteImport.update({
  id: '/archive/1',
  path: '/archive/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive/1': typeof Archive1Route
  '/archive/2': typeof Archive2Route
  '/archive/3': typeof Archive3Route
  '/archive/4': typeof Archive4Route
  '/archive/5': typeof Archive5Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
  id:
    | '__root__'
    | '/'
    | '/archive/1'
    | '/archive/2'
    | '/archive/3'
    | '/archive/4'
    | '/archive/5'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Archive1Route: typeof Archive1Route
  Archive2Route: typeof Archive2Route
  Archive3Route: typeof Archive3Route
  Archive4Route: typeof Archive4Route
  Archive5Route: typeof Archive5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/5': {
      id: '/archive/5'
      path: '/archive/5'
      fullPath: '/archive/5'
      preLoaderRoute: typeof Archive5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/4': {
      id: '/archive/4'
      path: '/archive/4'
      fullPath: '/archive/4'
      preLoaderRoute: typeof Archive4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/3': {
      id: '/archive/3'
      path: '/archive/3'
      fullPath: '/archive/3'
      preLoaderRoute: typeof Archive3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/2': {
      id: '/archive/2'
      path: '/archive/2'
      fullPath: '/archive/2'
      preLoaderRoute: typeof Archive2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/1': {
      id: '/archive/1'
      path: '/archive/1'
      fullPath: '/archive/1'
      preLoaderRoute: typeof Archive1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Archive1Route: Archive1Route,
  Archive2Route: Archive2Route,
  Archive3Route: Archive3Route,
  Archive4Route: Archive4Route,
  Archive5Route: Archive5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
